### ISSUE TITLE
test

### ISSUE THREAD

**Issue by Kirao** [FierceLands/Chat#3]
test

**Comment by Misterio77** [comment]
Ai depois que acabar é só clicar em close.

**Comment by Kirao** [comment]
????

**Comment by Misterio77** [comment]
Pra fechar o treco

**Comment by Misterio77** [comment]
Ou reabrir

**Comment by Misterio77** [comment]
;3

**Comment by Misterio77** [comment]
Tipo é como se fosse dizendo que resolveu o problema, ou nesse caso o assunto kkk
